"""Adding portion of the create pitch section

Revision ID: 7fe549764f62
Revises: e3c4fe53b134
Create Date: 2021-09-23 01:34:17.450269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe549764f62'
down_revision = 'e3c4fe53b134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minutepitches', sa.Column('pitchtitle', sa.String(length=255), nullable=True))
    op.add_column('minutepitches', sa.Column('postedat', sa.DateTime(), nullable=True))
    op.add_column('minutepitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'minutepitches', 'users', ['user_id'], ['id'])
    op.drop_column('minutepitches', 'postedby')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minutepitches', sa.Column('postedby', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'minutepitches', type_='foreignkey')
    op.drop_column('minutepitches', 'user_id')
    op.drop_column('minutepitches', 'postedat')
    op.drop_column('minutepitches', 'pitchtitle')
    # ### end Alembic commands ###
