"""Updating NewPitch DB

Revision ID: a75e350b0951
Revises: 7fe549764f62
Create Date: 2021-09-23 16:52:09.861492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75e350b0951'
down_revision = '7fe549764f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minutepitches', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('minutepitches', 'category')
    # ### end Alembic commands ###
